### ISSUE TITLE
[kolors] Load native ip-adapter in diffusers format

### ISSUE THREAD

**Issue by shauray8** [ModelsLab/diffusers_plus_plus#26]
Transfer these adapters to diffusers friendly format -
* Kwai-Kolors/Kolors-IP-Adapter-Plus
* Kwai-Kolors/Kolors-IP-Adapter-FaceID-Plus

**Comment by shauray8** [comment]
@abhinavjangra29

**Comment by AbhinavJangra29** [comment]
on it!

**Comment by shauray8** [comment]
main supports it
